name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # gera todo dia à meia-noite
  workflow_dispatch:     # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/snake.svg"
